# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [15]:
#1---Calculate-the-BMI-(body-mass-index)-on-the-two-lists-below-using-NDArrays...
import numpy as np
# formula = weight / (height**2) * 703
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]
height_arr = np.array(height)
weight_arr = np.array(weight)


BMI = (weight_arr / height_arr**2) * 703

print(BMI)


[16.24238605 17.21632653 18.12933942 18.98533951 19.78795271 20.54054054
 21.24622222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [34]:
def random_matrix(lower_bound, upper_bound, shape, dtype):
    rand_arr = np.random.uniform(lower_bound, upper_bound, shape)
#     rand_arr_int = np.random.randint(lower_bound, upper_bound, shape) # generates int
    return rand_arr.astype(dtype)

shape = (4, 5)
dtype = input("Enter type").strip()

try:
    result = random_matrix(1, 20, shape, dtype)
    print(result)
except ValueError as e:
    print(f'Value error {e}')

Enter typeint
[[15 19  8 10  3]
 [18  5 15 14 13]
 [13 17 15  2  3]
 [ 3  1  1  7 10]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [35]:
import csv
import numpy as np




In [58]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename, 
                        delimiter = d,
                        skip_header=1,
                        invalid_raise=False,
                        usecols = np.arange(0, 28),
                        names = FIELDS,
                        dtype = DATATYPES)
    return data


def diff(file1, file2):
    result_2017 = load_data(filename_2017)
    result_2018 = load_data(filename_2018)
    
    slg_2017 = result_2017['SLG']
    slg_2018 = result_2018['SLG']
    
    
    slg_2017_copy = slg_2017[:-3] # 2017 has 23 values and 2018 20 values, 
                                  #so i popped 3 values from 2017 to perform operations. 
                                  #bcz its not possible to perform operations on arrays having different length
    
    
    diff = slg_2018 - slg_2017_copy
    print(f'Difference: \n"{diff}"')
    
    result = '2018' if np.sum(diff) > 0 else '2017'

    print(f'\n"{result}" was a better year. ')

filename_2017 = 'files/redsox_2017_hitting.txt'
filename_2018 = 'files/redsox_2018_hitting.txt'
    
diff(filename_2017, filename_2018)


Difference: 
"[-0.125      -0.00999999 -0.00399998  0.11900002 -0.04899999  0.04100001
  0.00099999  0.181       0.20000002  0.05700001 -0.104      -0.005
 -0.14399996  0.26400003  0.04899999  0.06099999  0.04699999 -0.07799998
 -0.23700002 -0.139     ]"

"2018" was a better year. 
